LABEL ArchR
  LINUX /KERNEL
  FDTDIR /dtbs/
  ## FDT: don't forget the leading slash, remove all symbols after .dtb (including whitespace)
  # FDT /dtbs/your-custom-devicetree.dtb
  FDTOVERLAYS /overlays/mipi-panel.dtbo
  APPEND boot=${partition_boot} root=${partition_root} disk=${partition_storage} quiet console=ttyS2,1500000 console=tty0 loglevel=0 vt.global_cursor_default=0 consoleblank=0 net.ifnames=0 systemd.show_status=false mitigations=off audit=0 nowatchdog threadirqs zswap.enabled=0 loop.max_loop=16 uboot.hwid_adc=${hwid_adc}
